version: "3"
networks:
  br0:
    external: true
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=admin
      - PASS=qfq418
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /mnt/user/media/torrents:/media/torrents
      - /mnt/user/appdata/transmission:/config
    networks:
      br0:
        ipv4_address: 192.168.1.11
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    ports:
      - 8080:8080
      - 36671:36671
      - 36671:36671/udp
    volumes:
      - /mnt/user/media/torrents:/media/torrents
      - /mnt/user/appdata/qbittorrent:/config
    networks:
      br0:
        ipv4_address: 192.168.1.12
    restart: unless-stopped
  aria2-pro:
    image: p3terx/aria2-pro
    container_name: aria2-pro
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
      - RPC_SECRET=qfq418
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - UPDATE_TRACKERS=true
      - DISK_CACHE=64M
    ports:
      - 6800:6800
    volumes:
      - /mnt/user/downloads:/downloads
      - /mnt/user/media/torrents:/media/torrents
      - /mnt/user/appdata/aria2-config:/config
    networks:
      br0:
        ipv4_address: 192.168.1.13
    restart: unless-stopped
  # iyuuplus:
  #   image: iyuucn/iyuuplus
  #   container_name: iyuuplus
  #   environment:
  #     - PUID=99
  #     - PGID=100
  #     - UMASK=022
  #     - TZ=Asia/Shanghai
  #   ports:
  #     - 8787:8787
  #   volumes:
  #     - /mnt/user/appdata/transmission/:/transmission
  #     - /mnt/user/appdata/qbittorrent:/qbittorrent
  #     - /mnt/user/media/torrents:/media/torrents
  #     - /mnt/user/appdata/iyuuplus:/IYUU/db
  #   networks:
  #     br0:
  #       ipv4_address: 192.168.1.14
  #   restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    networks:
      br0:
        ipv4_address: 192.168.1.15
    restart: unless-stopped

  # jackett:
  #   image: lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   environment:
  #     - PUID=99
  #     - PGID=100
  #     - UMASK=022
  #     - TZ=Asia/Shanghai
  #   volumes:
  #     - /mnt/user/appdata/jackett:/config
  #   ports:
  #     - 9117:9117
  #   networks:
  #     br0:
  #       ipv4_address: 192.168.1.15
  #   restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/appdata/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      br0:
        ipv4_address: 192.168.1.16
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/media:/media
    ports:
      - 7878:7878
    networks:
      br0:
        ipv4_address: 192.168.1.17
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/media:/media
    ports:
      - 8989:8989
    networks:
      br0:
        ipv4_address: 192.168.1.18
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/appdata/bazarr:/config
      - /mnt/user/media:/media
    ports:
      - 6767:6767
    networks:
      br0:
        ipv4_address: 192.168.1.19
    restart: unless-stopped
    ombi:
      image: lscr.io/linuxserver/ombi:latest
      container_name: overseerr
      environment:
        - PUID=99
        - PGID=100
        - UMASK=022
        - TZ=Asia/Shanghai
      volumes:
        - /mnt/user/appdata/ombi:/config
      ports:
        - 3579:3579
      networks:
        br0:
          ipv4_address: 192.168.2.20
      restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/appdata/lidarr:/config
      - /mnt/user/media:/media
    ports:
      - 8686:8686
    networks:
      br0:
        ipv4_address: 192.168.1.21
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/appdata/readarr:/config
      - /mnt/user/media:/media
    ports:
      - 8787:8787
    networks:
      br0:
        ipv4_address: 192.168.1.22
    restart: unless-stopped

  # mylar3:
  #   image: lscr.io/linuxserver/mylar3:latest
  #   container_name: mylar3
  #   environment:
  #     - PUID=99
  #     - PGID=100
  #     - UMASK=022
  #     - TZ=Asia/Shanghai
  #   volumes:
  #     - /mnt/user/appdata/mylar3:/config
  #     - /mnt/user/media:/media
  #   ports:
  #     - 8090:8090
  #   networks:
  #     br0:
  #       ipv4_address: 192.168.1.23
  #   restart: unless-stopped

  # whisparr:
  #   image: cr.hotio.dev/hotio/whisparr:nightly
  #   container_name: whisparr
  #   environment:
  #     - PUID=99
  #     - PGID=100
  #     - UMASK=022
  #     - TZ=Asia/Shanghai
  #   volumes:
  #     - /mnt/user/appdata/whisparr:/config
  #     - /mnt/user/media:/media
  #   ports:
  #     - 6969:6969
  #   networks:
  #     br0:
  #       ipv4_address: 192.168.1.24
  #   restart: unless-stopped
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    volumes:
      - /mnt/user/appdata/chinesesubfinder/config:/config # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /media/media:/media/media # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - /mnt/user/appdata/chinesesubfinder/browser:/root/.cache/rod/browser # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    environment:
      - PUID=99 # uid
      - PGID=100 # gid
      - PERMS=true # 是否重设/media权限
      - TZ=Asia/Shanghai # 时区
      - UMASK=022 # 权限掩码
    restart: always
    ports:
      - 19035:19035 # 从0.20.0版本开始，通过webui来设置
      - 19037:19037 # webui 的视频列表读取图片用，务必设置不要暴露到外网
    networks:
      br0:
        ipv4_address: 192.168.1.25
    logging:
      driver: "json-file"
      options:
        max-size: "100m" # 限制docker控制台日志大小，可自行调整
