log:
  level: warn
  file: "./mosdns.log"

plugin:
  ################# 服务插件 ################

  # 启动服务器的插件
  - tag: main_server
    type: server
    args:
      entry:
        - _single_flight
        - main_sequence # 运行主执行序列
        - modify_ttl # 修改 ttl
      server:
        - protocol: udp
          addr: "[::]:5335"
        - protocol: tcp
          addr: "[::]:5335"
  ################# 可执行插件 ################

  # 缓存
  - tag: "mem_cache"
    type: "cache"
    args:
      size: 4096 # 条目数量
      lazy_cache_ttl: 86400 # lazy cache 生存时间
      lazy_cache_reply_ttl: 30 # 返回过期应答的 TTL

  - tag: "ecs-cn"
    type: "ecs"
    args:
      auto: true #仅适用于公网的服务器。本地运行不要启用这个功能。
      ipv4: "221.12.59.213" # 预设 IPv4
      force_overwrite: true # 强制覆盖
      mask4: 24 # 用于 ipv4 地址的掩码 默认: 24。
      mask6: 64 # 用于 ipv6 地址的掩码 默认: 48。

  # 修改应答 ttl
  - tag: "modify_ttl"
    type: "ttl"
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  ################ 序列 #################

  # main_sequence
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
           - query_ad # ad
          exec:
           - _block_with_nxdomain # 空应答
           - _return
        - mem_cache # 缓存
        - if:
            - query_zju
          exec:
            - _prefer_ipv4 # 优先 IPv4
            - localdns
            - _return
        - if:
            - query_cn # cn域名
            - "!_query_is_common" # 不常见的请求
          exec:
            - ecs-cn
            - _prefer_ipv4 # 优先 IPv4
            - _pad_query
            - local # 用本地服务器
            - if:
                - "response_cnip" # 结果是 cnip
              exec:
                - _return # 结束

        - if:
            - query_notcn # 已知的 非cn域名
          exec:
            - _prefer_ipv4 # 优先 IPv4
            - _pad_query
            - remote # 无污染
            - if:
                - "!response_cnip" # 结果是 非cnip
              exec:
                - _return # 结束

        - primary: #其他所有情况
            - _prefer_ipv4
            - _pad_query
            - remote
          secondary:
            - _prefer_ipv4
            - _pad_query
            - local
          fast_fallback: 400 # 这里建议设置成 local 服务器正常延时的 2~5 倍 单位: 毫秒
          always_standby: true

  # local 序列
  - tag: local
    type: sequence
    args:
      exec:
        - primary:
            - parallel: # 并行
                - - "ali" # 执行序列 #1。
                - - "dnspod" # 执行序列 #2。
          secondary:
            - localdns # 备用本地
          fast_fallback: 600 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true

  # remote 序列
  - tag: remote
    type: sequence
    args:
      exec:
        - primary:
            - parallel: # 并行
                - - "google" # 执行序列 #1。
                - - "cloudflare" # 执行序列 #2。
          secondary:
            - adguard # 备用 adguard
          fast_fallback: 600 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true

  ################ DNS #################
  # 阿里 dns
  - tag: ali
    type: forward
    args:
      upstream:
        - addr: "https://dns.alidns.com/dns-query" # 服务器地址
          ip_addr: "223.5.5.5"
          trusted: true # 是否是可信服务器

        - addr: "tls://dns.alidns.com" # 服务器地址
          ip_addr: "223.6.6.6"
          trusted: true # 是否是可信服务器


  # dnspod
  - tag: dnspod
    type: fast_forward
    args:
      upstream:
        - addr: "https://doh.pub/dns-query" # 服务器地址
          dial_addr: "119.29.29.29"
          trusted: true # 是否是可信服务器

        - addr: "tls://dot.pub" # 服务器地址
          dial_addr: "119.28.28.28"
          trusted: true # 是否是可信服务器

  # 本地 dns 备用
  - tag: localdns
    type: forward
    args:
      upstream:
        - addr: "10.10.0.21"
        - addr: "10.10.2.21"

  # google dns
  - tag: google
    type: fast_forward
    args:
      upstream:
        - addr: "https://dns.google/dns-query" # 服务器地址
          dial_addr: "8.8.4.4"
          trusted: true # 是否是可信服务器
          enable_pipeline: true
        - addr: "tls://dns.google" # 服务器地址
          dial_addr: "8.8.8.8"
          trusted: true # 是否是可信服务器
          enable_pipeline: true
      timeout: 5 # 请求超时时间秒

  # cloudflare
  - tag: cloudflare
    type: fast_forward
    args:
      upstream:
        - addr: "https://cloudflare-dns.com/dns-query" # 服务器地址
          dial_addr: "1.0.0.1"
          trusted: true # 是否是可信服务器
          enable_pipeline: true
        - addr: "tls://cloudflare-dns.com" # 服务器地址
          dial_addr: "1.1.1.1"
          trusted: true # 是否是可信服务器
          enable_pipeline: true
      timeout: 5 # 请求超时时间秒

  # doq 备用
  - tag: adguard
    type: fast_forward
    args:
      upstream:
        - addr: "tls://dns-unfiltered.adguard.com" # 服务器地址
          dial_addr: "94.140.14.140"
          trusted: true # 是否是可信服务器
          enable_pipeline: true

  ################ 匹配器 #################

  # 匹配zju内网
  - tag: query_zju
    type: query_matcher
    args:
      domain:
        - "zju.edu.cn"
        - "cc98.org"
        - "nexushd.org"
  # 查询 - cn 域名
  - tag: query_cn
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:cn"

  # 查询 - gfw
  - tag: query_gfw
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:gfw"

  # 查询 - 非 cn 域名
  - tag: query_notcn
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:geolocation-!cn"

  # 查询 - ad
  - tag: query_ad
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:category-ads-all"

  # 返回 - cn IP
  - tag: response_cnip
    type: response_matcher
    args:
      ip:
        - "ext:./geoip.dat:cn"
